### PR TITLE
Support for the official Pinterest api

### PR DESCRIPTION
**Pull request by nlsrchtr**
With the attached changes, this Omniauth strategy would support the official Pinterest auth workflow.

It would be great if you could merge this PR and also push a newer version of the gem. I already increased the gem version, but maybe you'll name it more final, like `2.0.0`.

### CODE REVIEW

**Comment by chikeabuah** [comment]
not sure how to upvote pull requests, so just want to second, would be great if you could update this to support official pinterest

**Comment by nlsrchtr** [comment]
Hi @chikeabuah, until @jot finds the time to release a new version you can go with:
```gem 'omniauth-pinterest', github: 'endil/omniauth-pinterest', branch: 'supporting-official-api'```
in your ```Gemfile```. I'll keep the repository up until the new gem is released.

@jot: If you give me access to the repository and RubyGems, I could help with the maintenance.

**Comment by nlsrchtr** [comment]
@jot: thanks! :+1:

**Comment by jot** [comment]
@nlsrchtr I've also made you an owner on RubyGems.

**Comment by nlsrchtr** [comment]
Great, thanks! Just released [version 2.0.0](https://rubygems.org/gems/omniauth-pinterest) and updated the repository.

**Comment by chikeabuah** [comment]
@jot @nlsrchtr thanks guys!

**Pull request merged**
